---
- name: "Ansible Config"
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Update OS
      apt:
        upgrade: dist
        autoremove: true
        autoclean: true
        update_cache: true
    - name: Required Software
      apt:
        pkg:
          - apt-transport-https
          - gh
          - jq
          - zsh
          - lsd
    - name: Change default shell to zsh for the user 'zeulewan'
      user:
        name: zeulewan
        shell: /usr/bin/zsh

        
