---
- name: "Ansible Config"
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Update OS
      apt:
        upgrade: dist
        autoremove: true
        autoclean: true
        update_cache: true
    - name: Required Software
      apt:
        pkg:
          - apt-transport-https
          - gh
          - jq
          - zsh
          - unzip
          - python3-pip
          - exa
    - name: Change default shell to zsh for the user 'zeulewan'
      user:
        name: zeulewan
        shell: /usr/bin/zsh
    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
    - name: Install shell-gpt
      pip:
        name: shell-gpt
        
        
