---
- name: "Ansible Config"
  hosts: localhost
  gather_facts: true

  tasks:
    - name: GIT config
      git_config:
          name: "{{ item.name }}"
          scope: global
          value: "{{ item.value }}"
      with_items:
          - {name: "credential.helper", value: "!/usr/bin/gh auth git-credential" }
          - {name: "user.name",  value: "Zeulewan Mordasiewicz" }
          - {name: "user.email", value: "zeul@mordasiewicz.com" }
          - {name: "ui.color",   value: "True" }
          - {name: "core.editor",   value: "vim" }
          - {name: "init.defaultBranch", value: "main" }

    - name: Add alias for python3
      lineinfile:
        path: "~/.bashrc"
        line: "alias py='python3'"
        create: yes
      become: no
      tags: alias
